spring.application.name=giteat
spring.profiles.active=dev
# spring.profiles.active=release # release


# DataBase Settings for dev
spring.datasource.url=jdbc:mysql://localhost:3306/test?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ssafy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# if you release, change ddl-auto value none or validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# DataBase Settings for release
#spring.datasource.url=jdbc:mysql://localhost:3306/schema_name?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=ssafy

# open AI
spring.ai.openai.api-key=value