spring.application.name=security

# ???? url ?? ??
# spring.mvc.servlet.path=/api

# security ?? ? ? restAPI ?? ?? ?? main URL
# api.base-url=http://i12b108.p.ssafy.io
api.base-url=http://localhost:8081

# GitLab OAuth2

oauth.gitlab.redirect-uri=http://127.0.0.1:5173/loading
oauth.gitlab.authorization-grant-type=authorization_code
oauth.gitlab.scope=read_user

# GitLab Provider
oauth.gitlab.authorization-uri=https://lab.ssafy.com/oauth/authorize
oauth.gitlab.token-uri=https://lab.ssafy.com/oauth/token
oauth.gitlab.user-info-uri=https://lab.ssafy.com/api/v4/user
oauth.gitlab.user-name-attribute=username

spring.profiles.include=secret

## Spring Cloud Gateway ??? ??
# ???? ?? ID
spring.cloud.gateway.routes[0].id=rest-container
# ?? ??? ??? ?? ??
spring.cloud.gateway.routes[0].uri=http://spring-rest:8080
# ?? ??? ??? ??(??)
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/rest/**

## test ???? ?? ? ??? ??
#spring.cloud.gateway.routes[1].id=test-container
#spring.cloud.gateway.routes[1].uri=http://spring-test:8080
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/test/**
