spring.application.name=security

# ???? url ?? ??
spring.mvc.servlet.path=/api

# security ?? ? ? restAPI ?? ?? ?? main URL
api.base-url=https://example.com/api
# api.base-url=""

# GitLab OAuth2
spring.security.oauth2.client.registration.gitlab.redirect-uri=http://localhost:8080/login/oauth2/callback/gitlab
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.scope=read_user

# GitLab Provider
spring.security.oauth2.client.provider.gitlab.authorization-uri=https://lab.ssafy.com/oauth/authorize
spring.security.oauth2.client.provider.gitlab.token-uri=https://lab.ssafy.com/oauth/token
spring.security.oauth2.client.provider.gitlab.user-info-uri=https://lab.ssafy.com/api/v4/user
spring.security.oauth2.client.provider.gitlab.user-name-attribute=username

