spring.application.name=security

# ???? url ?? ??
# spring.mvc.servlet.path=/api

# security ?? ? ? restAPI ?? ?? ?? main URL
api.base-url=http://i12b108.p.ssafy.io
# api.base-url=""

# GitLab OAuth2
spring.security.oauth2.client.registration.gitlab.redirect-uri=http://localhost:8080/login/oauth2/code/gitlab
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.scope=read_user


spring.security.oauth2.client.registration.gitlab.client-id=2adedad9065950161b2ff1671f8c6e13b1cc65354dc43d1ef36483416391424b
spring.security.oauth2.client.registration.gitlab.client-secret=gloas-369ddcd58ac0e4af7683e1b53ed95cde437a3a5b39f890c11ac1e39f2361daad

# GitLab Provider
spring.security.oauth2.client.provider.gitlab.authorization-uri=https://lab.ssafy.com/oauth/authorize
spring.security.oauth2.client.provider.gitlab.token-uri=https://lab.ssafy.com/oauth/token
spring.security.oauth2.client.provider.gitlab.user-info-uri=https://lab.ssafy.com/api/v4/user
spring.security.oauth2.client.provider.gitlab.user-name-attribute=username

server.port=8080