export const dummy = [
  {
    prId: 1,
    repoId: 1,
    userId: 1,
    title: "MR) 기본 로직 구현",
    description: "구현했습니당",
    createAt: null,
    isOpened: 1,
    targetBranch: "master",
    sourceBranch: "develop",
  },
  {
    prId: 2,
    repoId: 1,
    userId: 2,
    title: "#2 PR 업로드",
    description: "컨트롤러 수정했음",
    createAt: null,
    isOpened: 0,
    targetBranch: "develop",
    sourceBranch: "BE",
  },
  {
    prId: 3,
    repoId: 1,
    userId: 1,
    title: "Add feature X",
    description: "Implemented feature X to improve performance",
    createAt: [2025, 2, 1, 12, 0],
    isOpened: 1,
    targetBranch: "main",
    sourceBranch: "feature/x",
  },
  {
    prId: 4,
    repoId: 1,
    userId: 2,
    title: "Fix bug Y",
    description: "Resolved bug Y affecting user login",
    createAt: [2025, 2, 1, 13, 0],
    isOpened: 1,
    targetBranch: "main",
    sourceBranch: "bugfix/y",
  },
  {
    prId: 5,
    repoId: 1,
    userId: 3,
    title: "Update README",
    description: "Updated README with setup instructions",
    createAt: [2025, 2, 1, 14, 0],
    isOpened: 1,
    targetBranch: "main",
    sourceBranch: "docs/readme-update",
  },
  {
    prId: 6,
    repoId: 1,
    userId: 1,
    title: "나는송용인1X",
    description: "Implemented feature X to improve performance",
    createAt: [2025, 2, 1, 12, 0],
    isOpened: 1,
    targetBranch: "main",
    sourceBranch: "feature/x",
  },
  {
    prId: 7,
    repoId: 1,
    userId: 2,
    title: "나는송용인2Y",
    description: "Resolved bug Y affecting user login",
    createAt: [2025, 2, 1, 13, 0],
    isOpened: 1,
    targetBranch: "main",
    sourceBranch: "bugfix/y",
  },
  {
    prId: 8,
    repoId: 1,
    userId: 3,
    title: "나는송용인3",
    description: "Updated README with setup instructions",
    createAt: [2025, 2, 1, 14, 0],
    isOpened: 1,
    targetBranch: "main",
    sourceBranch: "docs/readme-update",
  },
];
