spring.application.name=ai
# DataBase Settings for dev
# DataBase Settings for release
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath:/mapper/*.xml


# JPA
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# open AI
spring.ai.openai.api-key=value
gpt.api.url=https://api.openai.com/v1/chat/completions

spring.profiles.include=secret

#server.port=8082