spring.application.name=notification

# DataBase Settings for dev
# DataBase Settings for release
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath:/mapper/*.xml






