spring.application.name=notification

# DataBase Settings for dev
# DataBase Settings for release
# spring.datasource.url=jdbc:mysql://i12b108.p.ssafy.io:3307/giteat?serverTimezone=UTC
spring.datasource.url=jdbc:mysql://giteat-db:3306/giteat?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# if you release, change ddl-auto value none or validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
mybatis.mapper-locations=classpath:/mapper/*.xml






